<?php

namespace Teckmeb\PtutBundle\Repository;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAppointment($teacher)
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('a')
            ->from('TeckmebPtutBundle:Ptut', 'p')
            ->from('TeckmebPtutBundle:Appointment' , 'a')
            ->where('p.teacher = :teacher')
            ->AndWhere('a.ptut = p')
            ->AndWhere('a.valide = 0')
            ->setParameter('teacher', $teacher);
        return $queryBuilder->getQuery()->getResult();
    }
}
