<?php

namespace Teckmeb\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindUser($name,$surname)
    {
        $query = $this->_em->createQuery('select u from TeckmebUserBundle:User u where LOWER(u.name) = :name and LOWER(u.surname) = :surname');
        $query->setParameter('name', $name)
            ->setParameter('surname', $surname);
        return $query
            ->getResult();
    }
}
