<?php

namespace Teckmeb\AdministrationBundle\Repository;

/**
 * CourseTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
