<?php

namespace Teckmeb\AdministrationBundle\Repository;

/**
 * TeachingUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeachingUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
