<?php

namespace Teckmeb\AbsenceBundle\Repository;

/**
 * AbsenceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
