<?php

namespace Teckmeb\AbsenceBundle\Repository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAbsence($student,$dateB,$dateE)
    {
        $query = $this->_em->createQuery('select a from TeckmebAbsenceBundle:Absence a where a.student = :student and (a.beginDate = :dateB or a.endDate = :dateE or a.endDate = :dateB or a.beginDate = :dateE)');
        $query->setParameter('student', $student);
        $query->setParameter('dateB', $dateB);
        $query->setParameter('dateE', $dateE);
        return $query->getResult();
    }
    
    public function myFindAbsenceByGroupeStudent($groupe, $student)
    {
        $query = $this->_em->createQuery('select a from TeckmebAbsenceBundle:Absence a where a.student = :student and a.groupe = :groupe');
        $query->setParameter('student', $student);
        $query->setParameter('groupe', $groupe);
        return $query->getResult();
    }
    
    public function myFindAbsenceBis($student,$dateB,$dateE,$id)
    {
        $query = $this->_em->createQuery('select a from TeckmebAbsenceBundle:Absence a where a.student = :student and a.id != :id and (a.beginDate = :dateB or a.endDate = :dateE or a.endDate = :dateB or a.beginDate = :dateE)');
        $query->setParameter('student', $student);
        $query->setParameter('dateB', $dateB);
        $query->setParameter('dateE', $dateE);
        $query->setParameter('id', $id);
        return $query->getResult();
    }

    public function myFindLast()
    {
        $now = new \DateTime();
        $query = $this->_em->createQuery('select a from TeckmebAbsenceBundle:Absence a, TeckmebCoreBundle:Semestre s, TeckmebCoreBundle:Groupe g where a.groupe = g and g.semestre = s and :date BETWEEN s.beginDate and s.endDate');
        $query->setParameter('date', $now);
    return $query
    ->getResult();
    }

    public function myFindAll($dateDebut, $dateFin)
    {
        $requete = "select a from TeckmebAbsenceBundle:Absence a ";
        $where = false;
        $parametre = array();
        if ($dateDebut != null)
        {
            $date = new \DateTime($dateDebut);
            $requete = $requete . ((!$where) ? "where a.beginDate >= :dateDebut " : "and a.beginDate >= :dateDebut ");
            $parametre['dateDebut'] = $date->format('Y-m-d');
            $where = true;
        }
        if($dateFin != null)
        {
            $requete = $requete . ((!$where) ? "where a.endDate <= :dateFin " : "and a.endDate <= :dateFin ");
            $parametre['dateFin'] = $dateFin;
            $where = true;
        }
        $query = $this->_em->createQuery($requete);
        if (count($parametre) > 0)
        {
            $query->setParameters($parametre);
        }
        return $query->getResult();
    }
}
