<?php

namespace Teckmeb\QuestionBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindQuestion($student)
    {
    $query = $this->_em->createQuery('select q from TeckmebQuestionBundle:Question q, TeckmebCoreBundle:Student s where q.student = :student or (s = :student and q.groupe MEMBER OF s.groupes)');
    $query->setParameter('student', $student);
    return $query->getResult();
    }
}
