<?php

namespace Teckmeb\TimeTableBundle\Repository;

/**
 * TimetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimetableRepository extends \Doctrine\ORM\EntityRepository
{
}
