<?php

namespace Teckmeb\ControlBundle\Repository;

/**
 * ControlTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindPromo()
    {
        $query = $this->_em->createQuery('select c from TeckmebControlBundle:ControlType c where c.controlTypeName = \'Promo\'');
        return $query->getResult(); 
    }
    
    public function myFindGroupe()
    {
        $query = $this->_em->createQuery('select c from TeckmebControlBundle:ControlType c where c.controlTypeName = \'Groupe\'');
        return $query->getResult(); 
    }

    /*
     * Récupère tous les type de controle
     */
    public function getTypeControl()
    {
        return $this->_em->createQueryBuilder()
        ->select('t')
        ->from($this->_entityName, 't');
    }
}
