<?php

namespace Teckmeb\ControlBundle\Repository;

use Teckmeb\CoreBundle\Entity\Education;
/**
 * ControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlRepository extends \Doctrine\ORM\EntityRepository
{
  public function myFindControl($teacher)
  {
    $now = new \DateTime();
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p, TeckmebCoreBundle:Semestre s, TeckmebCoreBundle:Groupe g where :date BETWEEN s.beginDate and s.endDate and g.semestre = s and  (c.education = e and e.teacher = :teacher and e.groupe = g) or (c.promo = p and p.subject = e.subject and e.teacher = :teacher and p.semestre = s)');
    $query->setParameter('teacher', $teacher);
    $query->setParameter('date', $now);
    // Méthode 1 : en passant par l'EntityManager
    /*$queryBuilder = $this->_em->createQueryBuilder()
      ->select('a')
      ->from($this->_entityName, 'a')
        ->join('a.education', 'b')
        ->join('a.promo', 'c')
        ->andWhere('b.teacher = :teacher')
        ->setParameter('teacher', $teacher)
        ->andWhere('a.education = b')
        ->orWhere('b.teacher = :teacher')
        ->setParameter('teacher', $teacher)
        ->andWhere('c.subject = b.subject')
        ->andWhere('a.promo = c');*/
    return $query
      ->getResult();
  }

  public function myFindControlType($teacher, $typeControl)
  {
    // Méthode 1 : en passant par l'EntityManager
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p, TeckmebCoreBundle:Semestre s, TeckmebCoreBundle:Groupe g where c.controlType = :typeControl and (s.active = 1 and g.semestre = s and (c.education = e and e.teacher = :teacher and e.groupe = g) or (c.promo = p and p.subject = e.subject and e.teacher = :teacher and p.semestre = s))');
    $query->setParameter('teacher', $teacher)
      ->setParameter('typeControl', $typeControl);
    return $query
      ->getResult();
  }
  public function myFindControlSubject($teacher, $subject)
  {
    // Méthode 1 : en passant par l'EntityManager
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p, TeckmebCoreBundle:Semestre s, TeckmebCoreBundle:Groupe g where s.active = 1 and g.semestre = s and (c.education = e and e.teacher = :teacher and e.subject = :subject and e.groupe = g) or (c.promo = p and p.subject = :subject and p.semestre = s)');
    $query->setParameter('teacher', $teacher)
      ->setParameter('subject', $subject);
    return $query
      ->getResult();
  }
  public function myFindControlGroupe($teacher, $groupe)
  {
    // Méthode 1 : en passant par l'EntityManager
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p where (c.education = e and e.teacher = :teacher and e.groupe = :groupe) or (c.promo = p and p.subject = e.subject and e.teacher = :teacher and e.groupe = :groupe)');
    $query->setParameter('teacher', $teacher)
      ->setParameter('groupe', $groupe);
    return $query
      ->getResult();
  }
  public function myFindControlSubjectType($teacher, $subject, $typeControl)
  {
    // Méthode 1 : en passant par l'EntityManager
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p, TeckmebCoreBundle:Semestre s, TeckmebCoreBundle:Groupe g where c.controlType = :typeControl and (s.active = 1 and g.semestre = s and (c.education = e and e.teacher = :teacher and e.subject = :subject and e.groupe = g) or (c.promo = p and e.teacher = :teacher and e.subject = :subject and p.subject = e.subject and p.semestre = s))');
    $query->setParameter('teacher', $teacher)
      ->setParameter('subject', $subject)
      ->setParameter('typeControl', $typeControl);
    return $query
      ->getResult();
  }
  public function myFindControlSubjectGroupe($teacher, $subject, $groupe)
  {
    // Méthode 1 : en passant par l'EntityManager
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p where (c.education = e and e.teacher = :teacher and e.groupe = :groupe and e.subject = :subject) or (c.promo = p and e.teacher = :teacher and e.groupe = :groupe and p.subject = e.subject and e.subject = :subject)');
    $query->setParameter('teacher', $teacher)
      ->setParameter('subject', $subject)
      ->setParameter('groupe', $groupe);
    return $query
      ->getResult();
  }
  public function myFindControlGroupeType($teacher, $typeControl, $groupe)
  {
    // Méthode 1 : en passant par l'EntityManager
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p where c.controlType = :typeControl and ((c.education = e and e.teacher = :teacher and e.groupe = :groupe) or (c.promo = p and p.subject = e.subject and e.teacher = :teacher and e.groupe = :groupe))');
    $query->setParameter('teacher', $teacher)
      ->setParameter('typeControl', $typeControl)
      ->setParameter('groupe', $groupe);
    return $query
      ->getResult();
  }
  public function myFindControlSubjectGroupeType($teacher, $subject, $groupe, $controlType)
  {
    // Méthode 1 : en passant par l'EntityManager
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p where c.controlType = :typeControl and ((c.education = e and e.teacher = :teacher and e.groupe = :groupe and e.subject = :subject) or (c.promo = p and e.teacher = :teacher and e.groupe = :groupe and p.subject = e.subject and e.subject = :subject))');
    $query->setParameter('teacher', $teacher)
      ->setParameter('subject', $subject)
      ->setParameter('typeControl', $controlType)
      ->setParameter('groupe', $groupe);
    return $query
      ->getResult();
  }
  public function myFindAllMark($student, $groupe)
  {
    $query = $this->_em->createQuery('select c, m from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p, TeckmebMarkBundle:Mark m where c = m.control and m.student = :student and (c.education = e and e.groupe = :groupe) or (c.promo = p and e = :groupe and p.subject = e.subject) order by e.subject,p.subject');
    $query->setParameter('student', $student)
      ->setParameter('groupe', $groupe);
    return $query
      ->getResult();
  }

  public function myFindAllControl($teacher, $subject = null, $groupe = null, $controlType = null)
  {
    $now = new \DateTime();
    $queryBuilder = $this->_em->createQueryBuilder()
      ->select('c')
      ->from($this->_entityName, 'c')
      ->join('TeckmebCoreBundle:Promo', 'p')
      ->join('TeckmebCoreBundle:Education', 'e')
      ->join('TeckmebCoreBundle:Groupe', 'g')
      ->join('TeckmebCoreBundle:Semestre', 's', 'with', ':date between s.beginDate and s.endDate')
      ->where('(c.education = e and e.teacher = :teacher and g.semestre = s and e.groupe = g) or (e.teacher = :teacher and p.subject = e.subject and c.promo = p and p.semestre = s)')->setParameter('date', $now)->setParameter('teacher', $teacher);
    if ($subject != null) {
      $queryBuilder->andWhere('e.subject = :subject and p.subject = :subject')->setParameter('subject', $subject);
    }
    if ($groupe != null) {
      $queryBuilder->andWhere('g = :groupe')->setParameter('groupe', $groupe);
    }
    if ($controlType != null) {
      $queryBuilder->andWhere('c.controlType = :controlType')->setParameter('controlType', $controlType);
    }
        /*$req = "select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBunlde:Promo where";
        $req += ($controlType != null) ? " c.controlType = :controlType" : "";
        $req += ($subject != null) ? " " : "";
        $req += ($groupe != null) ? " " : "";
        $query = $this->_em->createQuery($req);
        $query->setParameter('groupe', $groupe);
        $query->setParameter('controlType', $controlType);
        $query->setParameter('teacher', $teacher);
        return $query
            ->getResult();*/
    return $queryBuilder->getQuery()->getResult();
  }

  public function myFindControlGroupeBis($groupe)
  {
    // Méthode 1 : en passant par l'EntityManager
    $query = $this->_em->createQuery('select c from TeckmebControlBundle:Control c, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Promo p, TeckmebCoreBundle:Semestre s where (c.education = e and e.groupe = :groupe) or (c.promo = p and p.semestre = s and :groupe MEMBER OF s.groupes)');
    $query->setParameter('groupe', $groupe);
    return $query
      ->getResult();
  }
}
