<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * ChoixGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoixGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
