<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyGroupe($teacher)
    {
        $now = new \DateTime();
        $query = $this->_em->createQuery('select g from TeckmebCoreBundle:Groupe g, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Semestre s where e.teacher = :teacher and e.groupe = g and :date BETWEEN s.beginDate and s.endDate and g.semestre = s');
        $query->setParameter('teacher', $teacher);
        $query->setParameter('date', $now);
        return $query
            ->getResult();
    }

    /*
     * Récupère les groupes du professeur en paramêtre
     */
    public function getGroupesByTeacher($teacher)
    {
        $now = new \DateTime();
        return $this->_em->createQueryBuilder()
            ->select('g')
            ->from($this->_entityName, 'g')
            ->join('TeckmebCoreBundle:Education', 'e', 'with', 'e.groupe = g')
            ->join('TeckmebCoreBundle:Semestre', 's', 'with', 'g.semestre = s')
            ->where('e.teacher = :teacher and :date BETWEEN s.beginDate and s.endDate')
            ->setParameter('teacher', $teacher)
            ->setParameter('date', $now);
    }

    public function findActiveGroupes()
    {
        $now = new \DateTime();
        $query = $this->_em->createQuery('select g from TeckmebCoreBundle:Semestre s, TeckmebCoreBundle:Groupe g where g.semestre = s and :date BETWEEN s.beginDate and s.endDate');
        $query->setParameter('date', $now);
        return $query
            ->getResult();
    }

    public function findAllGroupe($subject)
    {
        $now = new \DateTime();
        $query = $this->_em->createQuery('select g from TeckmebCoreBundle:Groupe g, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Semestre se where e.subject = :subject and :date between se.beginDate and se.endDate and g.semestre = se and e.groupe = g');
        $query->setParameter('subject', $subject)
            ->setParameter('date', $now);
        return $query
            ->getResult();
    }

    public function findMyGroupes($teacher, $subject)
    {
        $now = new \DateTime();
        $query = $this->_em->createQuery('select g from TeckmebCoreBundle:Groupe g, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Semestre s where :date between s.beginDate and s.endDate and e.teacher = :teacher and e.groupe = g and e.subject = :subject and g.semestre = s');
        $query->setParameter('subject', $subject)->setParameter('date', $now)->setParameter('teacher', $teacher);
        return $query->getResult();
    }

    public function myfindGroupeBySemestre($semestre, $choixGroupe)
    {
        $query = $this->_em->createQuery('select g from TeckmebCoreBundle:Groupe g, TeckmebCoreBundle:Semestre s where g.semestre = :semestre and g.groupName = :choixGroupe');
        $query->setParameter('semestre', $semestre);
        $query->setParameter('choixGroupe', $choixGroupe);
        return $query
            ->getResult();
    }
}
