<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * OptionControllerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionControllerRepository extends \Doctrine\ORM\EntityRepository
{
}
