<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindPromo($subject, $semestre)
    {
        $query = $this->_em->createQuery('select p from TeckmebCoreBundle:Promo p where p.semestre = :semestre and p.subject = :subject');
        $query->setParameter('subject', $subject);
        $query->setParameter('semestre', $semestre);
        return $query->getResult();
    }

    public function getPromoTeacher($teacher)
    {
        $now = new \DateTime();
        return $this
            ->createQueryBuilder('p')
            ->join('p.semestre', 's','with' ,'p.semestre = s')
            ->join('p.subject', 'sub','with' ,'p.subject = sub')
            ->join('TeckmebCoreBundle:Teacher', 't' ,'with', 't = :teacher')
            ->where('sub MEMBER OF t.subjects')
            ->andWhere(':date between s.beginDate and s.endDate')
            ->setParameter('teacher', $teacher)
            ->setParameter('date', $now);
    }
}
