<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * SecretariatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretariatRepository extends \Doctrine\ORM\EntityRepository
{
}
