<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * SemestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemestreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActiveSemestre()
    {
        $now = new \DateTime();
        $query = $this->_em->createQuery('select s from TeckmebCoreBundle:Semestre s where :date BETWEEN s.beginDate and s.endDate');
        $query->setParameter('date', $now);
    return $query
    ->getResult();
    }
}
