<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindStudentByGroupe($groupe)
  {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('s')
            ->from('TeckmebCoreBundle:Student', 's')
            ->where(':groupe MEMBER OF s.groupes')
            ->setParameter('groupe',$groupe);
    return $queryBuilder->getQuery()->getResult();
}
}
