<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMySubject($teacher)
    {
        $now = new \DateTime();
        $query = $this->_em->createQuery('select su from TeckmebCoreBundle:Subject su, TeckmebCoreBundle:Education e, TeckmebCoreBundle:Semestre s, TeckmebCoreBundle:Groupe g where e.teacher = :teacher and e.subject = su and :date BETWEEN s.beginDate and s.endDate and g.semestre = s and e.groupe = g');
        $query->setParameter('teacher', $teacher);
        $query->setParameter('date', $now);
        return $query
            ->getResult();
    }

    /*
     * Récupère les sujets de groupe en cours appartenant au professeur passé en paramêtre
     */
    public function getSubjectByTeacher($teacher)
    {
        $now = new \DateTime();
        return $this->_em->createQueryBuilder()
            ->select('su')
            ->from($this->_entityName, 'su')
            ->join('TeckmebCoreBundle:Education', 'e', 'with', 'e.subject = su')
            ->join('TeckmebCoreBundle:Groupe', 'g', 'with', 'e.groupe = g')
            ->join('TeckmebCoreBundle:Semestre', 's', 'with', 'g.semestre = s')
            ->join('TeckmebCoreBundle:Teacher', 't', 'with', 't = :teacher')
            ->where('e.teacher = :teacher and :date BETWEEN s.beginDate and s.endDate')
            ->setParameter('teacher', $teacher)
            ->setParameter('date', $now);
    }
}
