<?php

namespace Teckmeb\CoreBundle\Repository;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindTeacherBySubject($subject)
  {
    /*$query = $this->_em->createQuery('select t from TeckmebCoreBundle:Teacher t where :subject MEMBER OF t.subjects');
        $query->setParameter('subject', $subject);*/
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('t')
            ->from('TeckmebCoreBundle:Teacher', 't')
            ->where(':subject MEMBER OF t.subjects')
            ->setParameter('subject',$subject);
            
    return $queryBuilder->getQuery()->getResult();
}
}
